name: GPP
main: me.theheyway.GPP.GPP
version: 0.1
description: >
             Generally Pleasing Plugin plugin.
commands:
  gpp:
    description: Displays information about the GPP.
    aliases: [generallypleasingplugin]
    permission: gpp.access
    usage: /gpp, /generallypleasingplugin - displays information about the plugin
  clear:
    description: Remove all items from yourself or another player.
    permission: gpp.overlord.clear
    usage: /clear - remove all your items
  cm:
    description: Enables or disabled creative mode.
    aliases: [creative, creativemode]
    permission: gpp.general.cm
    usage: /cm, /creative, /creativemode [player] - disable or enable creative mode
  cr:
    description: Reloads nearby chunks.
    aliases: [reloadchunk, chunkreload]
    permission: gpp.general.cr
    usage: /cr, /reloadchunk, /chunkreload - reloads nearby chunks
  page:
    description: Go to a specific page.
    permission: gpp.secretary
    usage: /page
  next:
    description: Next page.
    permission: gpp.secretary
    usage: /next
  prev:
    description: Previous page.
    permission: gpp.secretary
    usage: /prev
  flip:
    description: Flips a coin
    aliases: [flipcoin]
    permission: gpp.general.flipcoin
    usage: /flip, /flipcoin, /flip <player2> - Flips a coin
  heal:
    description: Heal a player
    permission: gpp.general.heal
    usage: /heal <player> <healAmount>
  freeze:
    description: Freezes or unfreezes a player.
    permission: gpp.cruelty.freeze
    usage: /freeze <player> - freezes/unfreezes a player
  home:
    description: Teleport home.
    permission: gpp.places.home
    usage: /home - teleplaces you home
  jumpto:
    description: Jump to crosshair location.
    aliases: [j]
    permission: gpp.places.jumpto
    usage: /jumpto, /j - jump to crosshair location
  point:
    description: Point your compass to spot.
    permission: gpp.general.point
    usage: /point - make your compass point to a location
  put:
    description: Teleport player to your crosshair.
    permission: gpp.places.put
    usage: /put <player> - teleport player to crosshair
  sethome:
    description: Set home.
    permission: gpp.places.sethome
    usage: /sethome - sets your home point
  setspawn:
    description: Set world spawn point.
    permission: gpp.places.setspawn
    usage: /setspawn - sets the world spawn point
  spawn:
    description: Teleport to spawn.
    permission: gpp.places.spawn
    usage: /spawn - teleplaces you to spawn
  strip:
    description: Strip a player of select items.
    permission: gpp.overlord.strip
    usage: /strip <player> <itemlist> - strips a player of select items
  summon:
    description: Teleport someone to you.
    permission: gpp.places.summon
    usage: /summon <player> - teleplaces someone to you
  test:
    description: I have no idea what this does.
    usage: /test
  tp:
    description: Teleport to another player.
    aliases: [teleport]
    permission: gpp.places.tp
    usage: /teleport, /tp - teleplaces you to another player
  balance:
    description: Displays your balance.
    aliases: [bal, cash, chingching, dough, money, wallet]
    permission: gpp.economos.balance
    usage:  /balance, /bal, /cash, /money [top [number]] - Display balance [of wealthiest]
  account:
    description: Display account information.
    aliases: [acc]
    permission: gpp.economos.account
    usage: /acc help - display more account commands
  pay:
    description: Pay another player.
    aliases: [givemoney]
    permission: gpp.economos.wallet.pay
    usage: /pay OR /givemoney <player> <amount> - Give a user a specified amount of money
  setbalance:
    description: Set a user's balance.
    aliases: [setbal]
    permission: gpp.economos.wallet.setbalance
    usage: /setbalance, /setbal - Set a user's balance
  cashin:
    description: Cash in levels for currency.
    permission: gpp.economos.cashin
    usage: /cashin <number of levels> - swap in levels for currency
  exchange:
    description: Check CashIn's exchange rate.
    permission: gpp.economos.exchange
    usage: /exchange - check the exchange rate per experience level

permissions:
  gpp.aye.allowed.miningexp:
    description: Allows players to get EXP from mining.
    default: true
  gpp.aye.allowed.placeore:
    description: Allows players to place ore blocks.
    default: op
  gpp.access:
    description: Top level access required to use any GPP command.
    default: true
  gpp.admin:
    description: Gives access to admin commands.
    default: op
    children:
      gpp.jumpto: true
      gpp.put: true
      gpp.sethomeother: true
      gpp.setspawn: true
      gpp.summon: true
      gpp.tp: true
      gpp.tpother: true
  gpp.general.cm:
    description: Enables or disabled creative mode.
    default: op
  gpp.general.cmother:
    description: Enables or disabled creative mode for another person.
    default: op
  gpp.general.cr:
    description: Reload chunks near you.
    default: true
  gpp.general.point:
    description: Allows player to point their compass to a location.
    default: true
  gpp.general.pointplayer:
    description: Allows player to point their compass at a player.
    default: op
  gpp.general.flipcoin:
    description: Flips a coin
    default: true
  gpp.general.heal:
    description: Heal a player
    default: op
  gpp.secretary:
    description: Allows player to use secretary.
    default: true
  gpp.cruelty.freeze:
    description: Freeze or unfreeze a player.
    default: op
  gpp.overlord.clear:
    description: Clear your inventory.
    default: true
  gpp.overlord.clearother:
    description: Clear another person's inventory.
    default: op
  gpp.overlord.strip:
    description: Strip certain items from a player.
    default: op
  gpp.places.home:
    description: Teleport home.
    default: true
  gpp.places.homeo:
    description: Teleport to another's home.
    default: op
  gpp.places.jumpto:
    description: Jump to location in crosshair.
    default: op
  gpp.places.put:
    description: Teleport player to your crosshair.
    default: op
  gpp.places.sethome:
    description: Set home.
    default: true
  gpp.places.sethomeo:
    description: Set the home of others.
    default: op
  gpp.places.setspawn:
    description: Set world spawn point.
    default: op
  gpp.places.spawn:
    description: Teleport to spawn.
    default: true
  gpp.places.summon:
    description: Teleport someone to you.
    default: op
  gpp.places.summonall:
    description: Teleport everyone in the server to you.
    default: op
  gpp.places.tp:
    description: Teleport to another player.
    default: op
  gpp.places.tpother:
    description: Teleport other players.
    default: op
  gpp.economos.access:
    description: Top level access required to use any Economos command.
    default: true
    children:
      economos.economy.access: true
  gpp.economos.admin:
    description: Allows admin access to Economos Economy.
    default: op
    children:
      gpp.economos.account.peek: true
      gpp.economos.account.createremote: true
      gpp.economos.account.setbalance: true
      gpp.economos.account.setinterest: true
      gpp.economos.account.setrole: true
      gpp.economos.wallet.setbalance: true
  gpp.economos.account:
    description: Allows user to use account commands.
    default: true
  gpp.economos.account.balance:
    description: Allows user to view account balances.
    default: true
  gpp.economos.account.create:
    description: Allows user to create new accounts.
    default: true
  gpp.economos.account.list:
    description: Allows user to view a list of their accounts.
    default: true
  gpp.economos.account.transfer:
    description: Allows a user to receive and transfer funds between accounts.
    default: true
  gpp.economos.account.setactive:
    description: Allows user to set an account to their active account.
    default: true
  gpp.economos.account.peek:
    description: Allows user to use basic account commands on other player accounts.
    default: op
  gpp.economos.account.remotecreate:
    description: Allows user to create remote accounts under any name, potentially for NPCs.
    default: op
  gpp.economos.account.remoteclose:
    description: Allows user to remotely close accounts with or without users, potentially for NPCs.
    default: op
  gpp.economos.account.remotetransfer:
    description: Allows user to transfer funds between accounts they do not own.
    default: op
  gpp.economos.account.setbalance:
    description: Allows user to set the balance of an account.
    default: op
  gpp.economos.account.setinterest:
    description: Allows user to set the interest of an account.
    default: op
  gpp.economos.account.setrole:
    description: Allows user to set the role of a player to a specific account.
    default: op
  gpp.economos.wallet.balance:
    description: Allows user to check their balance.
    default: true
  gpp.economos.wallet.setbalance:
    description: Allows user to set the balance of a wallet.
    default: op
  gpp.economos.wallet.pay:
    description: Allows user to pay another user.
    default: true
  gpp.economos.wallet.payable:
    description: Allows user to be paid by other users.
    default: true
  gpp.economos.wallet.top:
    description: Allows user to view the richest players on the server.
    default: true
  gpp.economos.cashin:
    description: Allows user to exchange levels for currency.
    default: true
  gpp.economos.checkexchange:
    description: Allows user to check the CashIn exchange rate.
    default: true
  gpp.economos.setexchange:
    description: Allows user to set the CashIn exchange rate.
    default: op