#-----------------------------------------------
# AreYouExperienced v.1.0
#
# Note that the amount of experience it takes to level up
# per level is based off this formula:
# 
# Experience = (level + 1) * 7
# 
# So to level up from level 0: 7 exp points
# Level 1: 14 exp points
# Level 2: 21 exp points
# 
# ...
# 
# Level 50: 357 exp
#
# These values range from 0 to any floating point value,
# with 100 counting as a whole experience point.
# 
# 700.0 = 7 exp points, or levelling up from level 0 to level 1.
#
# IMPORTANT:
# ALL VALUES MUST HAVE FLOATING POINT DECIMAL
# FORMAT (0.0, 12.56, 0.23, ETC)
#-----------------------------------------------
AreYouExperienced:
  ore_break_exp:
    coal_ore: 50.0
    diamond_ore: 500.0
    gold_ore: 350.0
    iron_ore: 150.0
    lapis_ore: 110.0
    obsidian: 180.0
    redstone_ore: 90.0
  #EXP per movement tick. Keep this *tiny*.
  traveling_exp: 0.05
  #EXP per new chunk generated via discovery.
  #You may not want to tell your players about
  #this one if you don't want your map getting HUGE.
  #:
  chunk_discover_exp: 0.5
  #EXP points to give a player for surviving
  #until dawn.
  still_alive_exp: 2000.0
  #EXP per point of damage taken.
  #1 point of damage = half a heart
  per_damage_exp: 50.0
  #EXP per point of damage done to a mob.
  #Keep in mind that you have to make up for
  #the amount of actual exp gained by how much
  #HP a mob has.
  mob_bonus_exp:
    #Blazes have 20 HP
    blaze: 30.0
    #Cave Spiders have 20 HP
    cavespider: 20.0
    #Chickens have 4 HP
    chicken: 25.0
    #Creepers have 20 HP
    creeper: 30.0
    #Cows have 10 HP
    cow: 20.0
    #Endermen have 40 HP
    enderman: 30.0
    #Ghasts have 10 HP
    ghast: 70.0
    #Magma cubes have 20, 6, and 2 HP
    magmacube_large: 20.0
    magmacube_medium: 15.0
    magmacube_small: 10.0
    #Mooshrooms have 10 HP
    mooshroom: 20.0
    #Pigs have 10 HP
    pig: 20.0
    #Sheep have 8 HP
    sheep: 20.0
    #Silverfish have 8 HP
    silverfish: 25.0
    #Skeletons have 20 HP
    skeleton: 20.0
    #Slimes have 32, 16, 4, and 1 HP
    slime_huge: 25.0
    slime_large: 20.0
    slime_medium: 15.0
    slime_small: 10.0
    #Snow golems have 4 HP
    snow_golem: 25.0
    #Spiders have 16 HP
    spider: 20.0
    #Spider jockeys have 16 HP -- CURRENTLY NOT IMPLEMENTED
    spiderjockey: 20.0
    #Squid have 10 HP
    squid: 20.0
    #Villagers have 20 HP
    villager: 20.0
    #Wild wolves have 8 HP, tamed 20 HP
    wolf: 35.0
    #Zombies have 20 HP
    zombie: 20.0
    #Zombie pigmen have 20 HP
    zombiepigman: 30.0